[shell]

font_family = "CaskaydiaMono Nerd Font"

time_format = "{:%H:%M}"
date_format = "%a, %b %d"

clipboard_enabled = true
clipboard_history_max_entries = 100
clipboard_auto_paste = "auto"

offline_mode = false
telemetry_enabled = false

show_location = true

ui_scale = 1.0
corner_radius_scale = 1.0


[shell.launcher]
app_grid = false
categories = true
compact = false
show_icons = true
sort_by_usage = true
session_search = true